version: '3.9'

services:
  service-auth:
    build: ./service-auth/
    container_name: service-auth
    restart: always
    networks:
      - ms-net
    ports:
      - 8000:8000
    # depends_on:
    #   nt-rabbitmq:
    #     condition: service_healthy
    environment:
      - PORT=8000
      - MONGO_USER=root
      - MONGO_PASS=p@ssw0rd2023
      - MONGO_DATABASE=rest-api
      - MONGO_IP=mongo
      - MONGO_PORT=27017
      - MONGO_AUTH=admin
      - MONGO_TIMEOUT=30000
      - RABBITMQ_URL=amqp://rabbitmq:1jj395qu@nt-rabbitmq:5672
  service-mail:
    build: ./service-mail/
    container_name: service-mail
    restart: always
    networks:
      - ms-net
    ports:
      - 8001:8001
    environment:
      - GMAIL_USERNAME=
      - GMAIL_PASSWORD=
      - RABBITMQ_URL=amqp://rabbitmq:1jj395qu@nt-rabbitmq:5672
      - LINE_URL_NOTIFY=https://notify-api.line.me/api/notify
      - LINE_TOKEN=
    depends_on:
      # - nt-rabbitmq
      - service-auth
networks:
  ms-net:
    name: ms-net
