version: '3.9'
networks:
  ms-net:
    name: ms-net
services:
  nt-rabbitmq:
    image: rabbitmq:3.11-management
    container_name: nt-rabbitmq
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - ms-net
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=1jj395qu
  mongo:
    image: mongo:6.0.3
    container_name: mongo
    restart: always
    networks:
      - ms-net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=p@ssw0rd2023
      - MONGO_INITDB_DATABASE=node-rest-api
    ports:
      - 27017:27017