version: '3.9'
networks:
  ms-net:
    name: ms-net
services:
  nt-rabbitmq:
    image: rabbitmq:3.11-management
    container_name: nt-rabbitmq
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - ms-net
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=1jj395qu
  mongo:
    image: mongo:6.0.3
    container_name: mongo
    restart: always
    networks:
      - ms-net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=p@ssw0rd2023
      - MONGO_INITDB_DATABASE=node-rest-api
    ports:
      - 27017:27017
  service-auth:
    build: ./service-auth/
    container_name: service-auth
    restart: always
    networks:
      - ms-net
    ports:
      - 8000:8000
    depends_on:
      nt-rabbitmq:
        condition: service_healthy
    environment:
      - PORT=8000
      - MONGO_USER=root
      - MONGO_PASS=p@ssw0rd2023
      - MONGO_DATABASE=rest-api
      - MONGO_IP=mongo
      - MONGO_PORT=27017
      - MONGO_AUTH=admin
      - MONGO_TIMEOUT=30000
      - RABBITMQ_URL=amqp://rabbitmq:1jj395qu@nt-rabbitmq:5672
  service-mail:
    build: ./service-mail/
    container_name: service-mail
    restart: always
    networks:
      - ms-net
    ports:
      - 8001:8001
    environment:
      - GMAIL_USERNAME=
      - GMAIL_PASSWORD=
      - RABBITMQ_URL=amqp://rabbitmq:1jj395qu@nt-rabbitmq:5672
      - LINE_URL_NOTIFY=https://notify-api.line.me/api/notify
      - LINE_TOKEN=
    depends_on:
      - nt-rabbitmq
      - service-auth
